export const TYPES = [
  {
    type: 'normal',
    color: '#aaaa99',
    offense: [
      { target: 'rock', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'ghost', effect: 0 },
    ],
    defense: [
      { target: 'ghost', effect: 0 },
      { target: 'fighting', effect: 2 },
    ],
  },
  {
    type: 'fire',
    color: '#ff4422',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'dragon', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ice', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
    ],
    defense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'ground', effect: 2 },
      { target: 'grass', effect: 0.5 },
      { target: 'ice', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
    ],
  },
  {
    type: 'water',
    color: '#3399ff',
    offense: [
      { target: 'fire', effect: 2 },
      { target: 'water', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ground', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'dragon', effect: 0.5 },
    ],
    defense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 0.5 },
      { target: 'grass', effect: 2 },
      { target: 'electric', effect: 2 },
      { target: 'ice', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
    ],
  },
  {
    type: 'electric',
    color: '#ffcc33',
    offense: [
      { target: 'water', effect: 2 },
      { target: 'electric', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ground', effect: 0 },
      { target: 'flying', effect: 2 },
      { target: 'dragon', effect: 0.5 },
    ],
    defense: [
      { target: 'electric', effect: 0.5 },
      { target: 'ground', effect: 2 },
      { target: 'flying', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
    ],
  },
  {
    type: 'grass',
    color: '#77cc55',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'poison', effect: 0.5 },
      { target: 'flying', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'dragon', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'water', effect: 2 },
      { target: 'ground', effect: 2 },
      { target: 'rock', effect: 2 },
    ],
    defense: [
      { target: 'water', effect: 0.5 },
      { target: 'electric', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ground', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'ice', effect: 2 },
      { target: 'poison', effect: 2 },
      { target: 'flying', effect: 2 },
      { target: 'bug', effect: 2 },
    ],
  },
  {
    type: 'ice',
    color: '#66ccff',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 0.5 },
      { target: 'ice', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'grass', effect: 2 },
      { target: 'ground', effect: 2 },
      { target: 'flying', effect: 2 },
      { target: 'dragon', effect: 2 },
    ],
    defense: [
      { target: 'ice', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'fighting', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'steel', effect: 2 },
    ],
  },
  {
    type: 'fighting',
    color: '#bb5544',
    offense: [
      { target: 'poison', effect: 0.5 },
      { target: 'flying', effect: 0.5 },
      { target: 'psychic', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
      { target: 'normal', effect: 2 },
      { target: 'ice', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'dark', effect: 2 },
      { target: 'steel', effect: 2 },
      { target: 'ghost', effect: 0 },
    ],
    defense: [
      { target: 'bug', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'dark', effect: 0.5 },
      { target: 'flying', effect: 2 },
      { target: 'psychic', effect: 2 },
      { target: 'fairy', effect: 2 },
    ],
  },
  {
    type: 'poison',
    color: '#aa5599',
    offense: [
      { target: 'poison', effect: 0.5 },
      { target: 'ground', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'ghost', effect: 0.5 },
      { target: 'ghost', effect: 0.5 },
      { target: 'grass', effect: 2 },
      { target: 'fairy', effect: 2 },
      { target: 'steel', effect: 0 },
    ],
    defense: [
      { target: 'grass', effect: 0.5 },
      { target: 'fighting', effect: 0.5 },
      { target: 'poison', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
      { target: 'ground', effect: 2 },
      { target: 'psychic', effect: 2 },
    ],
  },
  {
    type: 'ground',
    color: '#ddbb55',
    offense: [
      { target: 'grass', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'electric', effect: 2 },
      { target: 'poison', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'steel', effect: 2 },
      { target: 'flying', effect: 0 },
    ],
    defense: [
      { target: 'poison', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'water', effect: 2 },
      { target: 'grass', effect: 2 },
      { target: 'ice', effect: 2 },
      { target: 'electric', effect: 0 },
    ],
  },
  {
    type: 'flying',
    color: '#8899ff',
    offense: [
      { target: 'electric', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'grass', effect: 2 },
      { target: 'fighting', effect: 2 },
      { target: 'bug', effect: 2 },
    ],
    defense: [
      { target: 'grass', effect: 0.5 },
      { target: 'fighting', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'electric', effect: 2 },
      { target: 'ice', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'ground', effect: 0 },
    ],
  },
  {
    type: 'psychic',
    color: '#ff5599',
    offense: [
      { target: 'psychic', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fighting', effect: 2 },
      { target: 'poison', effect: 2 },
      { target: 'dark', effect: 0 },
    ],
    defense: [
      { target: 'fighting', effect: 0.5 },
      { target: 'psychic', effect: 0.5 },
      { target: 'bug', effect: 2 },
      { target: 'ghost', effect: 2 },
      { target: 'dark', effect: 2 },
    ],
  },
  {
    type: 'bug',
    color: '#aabb22',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'fighting', effect: 0.5 },
      { target: 'poison', effect: 0.5 },
      { target: 'flying', effect: 0.5 },
      { target: 'ghost', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
      { target: 'grass', effect: 2 },
      { target: 'psychic', effect: 2 },
      { target: 'dark', effect: 2 },
    ],
    defense: [
      { target: 'grass', effect: 0.5 },
      { target: 'fighting', effect: 0.5 },
      { target: 'ground', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'flying', effect: 2 },
      { target: 'rock', effect: 2 },
    ],
  },
  {
    type: 'rock',
    color: '#bbaa67',
    offense: [
      { target: 'fighting', effect: 0.5 },
      { target: 'ground', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'ice', effect: 2 },
      { target: 'flying', effect: 2 },
      { target: 'bug', effect: 2 },
    ],
    defense: [
      { target: 'normal', effect: 0.5 },
      { target: 'fire', effect: 0.5 },
      { target: 'poison', effect: 0.5 },
      { target: 'flying', effect: 0.5 },
      { target: 'water', effect: 2 },
      { target: 'grass', effect: 2 },
      { target: 'fighting', effect: 2 },
      { target: 'ground', effect: 2 },
      { target: 'steel', effect: 2 },
    ],
  },
  {
    type: 'ghost',
    color: '#6666bb',
    offense: [
      { target: 'dark', effect: 0.5 },
      { target: 'ghost', effect: 2 },
      { target: 'psychic', effect: 2 },
      { target: 'normal', effect: 2 },
    ],
    defense: [
      { target: 'poison', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'ghost', effect: 2 },
      { target: 'dark', effect: 2 },
      { target: 'normal', effect: 0 },
      { target: 'fighting', effect: 0 },
    ],
  },
  {
    type: 'dragon',
    color: '#7766ee',
    offense: [
      { target: 'steel', effect: 0.5 },
      { target: 'dragon', effect: 2 },
      { target: 'fairy', effect: 0 },
    ],
    defense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 0.5 },
      { target: 'electric', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ice', effect: 2 },
      { target: 'dragon', effect: 2 },
      { target: 'fairy', effect: 2 },
    ],
  },
  {
    type: 'dark',
    color: '#775544',
    offense: [
      { target: 'fighting', effect: 0.5 },
      { target: 'dark', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
      { target: 'pyschic', effect: 2 },
      { target: 'ghost', effect: 2 },
    ],
    defense: [
      { target: 'ghost', effect: 0.5 },
      { target: 'dark', effect: 0.5 },
      { target: 'fighting', effect: 2 },
      { target: 'bug', effect: 2 },
      { target: 'fairy', effect: 2 },
      { target: 'psychic', effect: 0 },
    ],
  },
  {
    type: 'steel',
    color: '#aaaabb',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'water', effect: 0.5 },
      { target: 'electric', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'ice', effect: 2 },
      { target: 'rock', effect: 2 },
      { target: 'fairy', effect: 2 },
    ],
    defense: [
      { target: 'normal', effect: 0.5 },
      { target: 'grass', effect: 0.5 },
      { target: 'ice', effect: 0.5 },
      { target: 'flying', effect: 0.5 },
      { target: 'psychic', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'rock', effect: 0.5 },
      { target: 'dragon', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fairy', effect: 0.5 },
      { target: 'fire', effect: 2 },
      { target: 'fighting', effect: 2 },
      { target: 'ground', effect: 2 },
      { target: 'poison', effect: 0 },
    ],
  },
  {
    type: 'fairy',
    color: '#ee99ee',
    offense: [
      { target: 'fire', effect: 0.5 },
      { target: 'poison', effect: 0.5 },
      { target: 'steel', effect: 0.5 },
      { target: 'fighting', effect: 2 },
      { target: 'dragon', effect: 2 },
      { target: 'dark', effect: 2 },
    ],
    defense: [
      { target: 'fighting', effect: 0.5 },
      { target: 'bug', effect: 0.5 },
      { target: 'dark', effect: 0.5 },
      { target: 'poison', effect: 2 },
      { target: 'steel', effect: 2 },
      { target: 'dragon', effect: 0 },
    ],
  },
];
